listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/srv/ftp
no_anon_password=YES
hide_ids=YES
ftpd_banner=VulnLab FTP ready.
pasv_enable=NO
xferlog_enable=YES
connect_from_port_20=YES
seccomp_sandbox=NO
